/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Documento;
import EDD.Usuario;
import Ejecutable.main;

/**
 *
 * @author S. Estefania, G. Angelo y S. Jose
 */
public class EliminarDocumento extends javax.swing.JFrame {

    /**
    * Constructor de la clase EliminarDocumento. Inicializa los componentes de la interfaz
    * y establece la ubicación relativa de la ventana en el centro de la pantalla. Llena el
    * desplegable de usuarios con los nombres de los usuarios existentes en la tabla hash.
    * Si no hay usuarios, imprime un mensaje en la consola.
    */
    public EliminarDocumento() {
        initComponents();
        this.setLocationRelativeTo(null);
        if (main.hashtable.getTamaño() == 0) {
            System.out.println("La base de usuarios esta vacia");
        } else {
            for (int i = 0; i < main.hashtable.getTamaño(); i++) {
                if (main.hashtable.arreglo[i] != null) {
                    this.Usuarios.addItem(main.hashtable.arreglo[i].getNombre());
                    Usuario aux = main.hashtable.arreglo[i].getpSig();
                    while (aux != null) {
                        this.Usuarios.addItem(aux.getNombre());
                        aux = aux.getpSig();
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TUsuario = new javax.swing.JLabel();
        TDocumento = new javax.swing.JLabel();
        Usuarios = new javax.swing.JComboBox<>();
        Documentos = new javax.swing.JComboBox<>();
        Cancelar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("Eliminar Documento");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        TUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TUsuario.setText("Usuario:");
        jPanel1.add(TUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, 30));

        TDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TDocumento.setText("Documento:");
        jPanel1.add(TDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 210, 30));

        Documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentosActionPerformed(evt);
            }
        });
        jPanel1.add(Documentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 210, 30));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Maneja el evento de eliminación de un documento. Obtiene el nombre del usuario seleccionado
    * en el desplegable, busca el usuario correspondiente en la tabla hash y elimina el documento
    * seleccionado del desplegable de documentos asociados a ese usuario. Luego, vuelve a mostrar
    * la ventana principal y cierra la ventana actual.
    *
    * @param evt Objeto de evento que representa la acción de eliminación.
    *
    * @author S. Estefania, G. Angelo y S. Jose
    */
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String usuario = Usuarios.getSelectedItem().toString();
        Usuario actual = main.hashtable.buscarUsuario(usuario);
        actual.eliminarDocumento(Documentos.getSelectedItem().toString());
        main.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed

        main.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosActionPerformed

    /**
    * Maneja el evento del botón que actualiza la lista de documentos disponibles para eliminar.
    * Obtiene el nombre del usuario seleccionado en el desplegable, busca el usuario correspondiente
    * en la tabla hash y actualiza la lista de documentos asociados a ese usuario. Luego, limpia el
    * desplegable de documentos y agrega los documentos disponibles para eliminar (con tiempo igual a -1).
    *
    * @param evt Objeto de evento que representa la acción del botón de actualización.
    *
    * @author S. Estefania, G. Angelo y S. Jose
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = Usuarios.getSelectedItem().toString();
        Usuario actual = main.hashtable.buscarUsuario(usuario);
        if (actual.getpPrim() == null) {
            this.Documentos.removeAllItems();
        } else {
            Documento aux = actual.getpPrim();
            this.Documentos.removeAllItems();
            while (aux != null) {
                if (aux.getTiempo() == -1) {

                    this.Documentos.addItem(aux.getNombre());

                }
                aux = aux.getpSig();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> Documentos;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel TDocumento;
    private javax.swing.JLabel TUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
