/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Documento;
import EDD.Usuario;
import Ejecutable.main;

/**
 *
 * @author evaas
 */
public class EliminarDocCola extends javax.swing.JFrame {
    
    /**
    * Constructor de la clase EliminarDocCola.
    * Inicializa los componentes de la interfaz y centra la ventana en la pantalla.
    * Llena el menú desplegable de usuarios con los usuarios disponibles si la base de usuarios no está vacía.
    * Si la base de usuarios está vacía, imprime un mensaje en la consola.
    */
    public EliminarDocCola() {
        initComponents();
        this.setLocationRelativeTo(null);
        if (main.hashtable.getTamaño() == 0) {
            System.out.println("La base de usuarios esta vacia");
        } else {
            for (int i = 0; i < main.hashtable.getTamaño(); i++) {
                if (main.hashtable.arreglo[i] != null) {
                    this.Usuarios.addItem(main.hashtable.arreglo[i].getNombre());
                    Usuario aux = main.hashtable.arreglo[i].getpSig();
                    while (aux != null) {
                        this.Usuarios.addItem(aux.getNombre());
                        aux = aux.getpSig();
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TUsuario = new javax.swing.JLabel();
        Usuarios = new javax.swing.JComboBox<>();
        TDocumento = new javax.swing.JLabel();
        DocumentosEnCola = new javax.swing.JComboBox<>();
        Eliminar = new javax.swing.JButton();
        Cancelar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Titulo.setText("Eliminar Documento de la Cola de Impresión");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        TUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TUsuario.setText("Usuario:");
        jPanel1.add(TUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 170, 30));

        TDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TDocumento.setText("Documento:");
        jPanel1.add(TDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        DocumentosEnCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentosEnColaActionPerformed(evt);
            }
        });
        jPanel1.add(DocumentosEnCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, 30));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        Cancelar1.setText("Cancelar");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Método invocado al hacer clic en el botón "Eliminar" en la interfaz EliminarDocCola.
    * Obtiene el usuario seleccionado y busca el documento seleccionado en la cola de impresión de ese usuario.
    * Si el documento se encuentra, cancela su impresión en la cola de montículo binario.
    * Finalmente, vuelve a mostrar la ventana principal y cierra la ventana actual.
    *
    * @param evt Evento de acción que desencadena este método.
    */
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        String usuario = Usuarios.getSelectedItem().toString();
        Usuario actual = main.hashtable.buscarUsuario(usuario);
        String documento = this.DocumentosEnCola.getSelectedItem().toString();
        Documento aux = actual.getpPrim();
        while (aux != null) {
            if (aux.getNombre().equals(documento)) {
                main.monticulo.cancelarImpresion(aux);
                break;
            }
            aux = aux.getpSig();
        }
        main.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarActionPerformed

    private void DocumentosEnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentosEnColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentosEnColaActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosActionPerformed

    /**
    * Acción realizada al presionar el botón "cerrar" en la interfaz de usuario.
    *
    * @param evt El evento de acción que desencadenó esta acción.
    * @author S. Estefania, G. Angelo y S. Jose
    */
    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
        main.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cancelar1ActionPerformed

    /**
    * Método invocado al hacer clic en el botón "Actualizar Documentos" en la interfaz EliminarDocCola.
    * Obtiene el usuario seleccionado, busca sus documentos en la cola de impresión y actualiza el
    * contenido del desplegable de documentos en cola. Si no hay documentos en la cola, se vacía el desplegable.
    *
    * @param evt Evento de acción que desencadena este método.
    *
    * @author S. Estefania, G. Angelo y S. Jose
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = Usuarios.getSelectedItem().toString();
        Usuario actual = main.hashtable.buscarUsuario(usuario);
        if (actual.getpPrim() == null) {
            this.DocumentosEnCola.removeAllItems();
        } else {
            this.DocumentosEnCola.removeAllItems();
            Documento aux = actual.getpPrim();
            while (aux != null) {
                if (aux.getTiempo() != -1) {
                    this.DocumentosEnCola.addItem(aux.getNombre());
                }
                aux = aux.getpSig();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus lTitulo feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarDocCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarDocCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarDocCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarDocCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarDocCola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar1;
    private javax.swing.JComboBox<String> DocumentosEnCola;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel TDocumento;
    private javax.swing.JLabel TUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
