/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.HashTable;
import EDD.MonticuloBinario;
import EDD.Usuario;
import Ejecutable.main;
import static Ejecutable.main.func;
import static Ejecutable.main.hashtable;
import Extras.Funciones;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author S. Estefania, G. Angelo y S. Jose
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    
    
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        AgregarUsuario = new javax.swing.JButton();
        CargarArchivo = new javax.swing.JButton();
        EliminarUsuario = new javax.swing.JButton();
        VerUsuarios = new javax.swing.JButton();
        ColaSecuencia = new javax.swing.JButton();
        ColaArbol = new javax.swing.JButton();
        LiberarImpresora = new javax.swing.JButton();
        EliminarDocDeLaCola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EliminarDocumento1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CrearDocumento1 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        EnviarACola = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarUsuario.setText("Agregar Usuario");
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, 20));

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, 20));

        EliminarUsuario.setText("Eliminar Usuario");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 130, 20));

        VerUsuarios.setText("Ver Usuarios");
        VerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(VerUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 110, 20));

        ColaSecuencia.setText("Cola de Impresión (Secuencia)");
        ColaSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaSecuenciaActionPerformed(evt);
            }
        });
        jPanel1.add(ColaSecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 240, 20));

        ColaArbol.setText("Cola de Impresión (Árbol)");
        ColaArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaArbolActionPerformed(evt);
            }
        });
        jPanel1.add(ColaArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 240, 20));

        LiberarImpresora.setText("Liberar Impresora");
        LiberarImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiberarImpresoraActionPerformed(evt);
            }
        });
        jPanel1.add(LiberarImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 240, 20));

        EliminarDocDeLaCola.setText("Eliminar Documento de la Cola");
        EliminarDocDeLaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDocDeLaColaActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarDocDeLaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 240, 20));

        jLabel1.setText("CONTROL DE LA COLA DE IMPRESIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, 10));

        jLabel2.setText("GESTIÓN DE USUARIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 10));

        EliminarDocumento1.setText("Eliminar Documento");
        EliminarDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDocumento1ActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 20));

        jLabel3.setText("GESTIÓN DE DOCUMENTOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 10));

        CrearDocumento1.setText("Crear Documento");
        CrearDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDocumento1ActionPerformed(evt);
            }
        });
        jPanel1.add(CrearDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, 20));

        Salir.setText("X");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 20));

        EnviarACola.setText("Enviar Documento a Cola");
        EnviarACola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarAColaActionPerformed(evt);
            }
        });
        jPanel1.add(EnviarACola, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 190, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo PrintEDD.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        AgregarUsuario ventana2 = new AgregarUsuario();
        this.setVisible(false);
        ventana2.setVisible(true);
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void VerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerUsuariosActionPerformed

        VerUsuarios V6 = new VerUsuarios();
        this.setVisible(false);
        V6.setVisible(true);
    }//GEN-LAST:event_VerUsuariosActionPerformed

    private void ColaSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaSecuenciaActionPerformed
        main.monticulo.visualizarGrafo();
    }//GEN-LAST:event_ColaSecuenciaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        EliminarUsuario V4 = new EliminarUsuario();
        this.setVisible(false);
        V4.setVisible(true);
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        main.func.abrir_archivo();
        try {
            main.hashtable.leer_db();
        } catch (IOException ex) {
            Logger.getLogger(Ventana1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void ColaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaArbolActionPerformed
        main.monticulo.visualizarMonticulo();
    }//GEN-LAST:event_ColaArbolActionPerformed

    private void LiberarImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiberarImpresoraActionPerformed
        main.monticulo.imprimirDocumento();
    }//GEN-LAST:event_LiberarImpresoraActionPerformed

    private void EliminarDocDeLaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocDeLaColaActionPerformed
        EliminarDocCola V9 = new EliminarDocCola();
        this.setVisible(false);
        V9.setVisible(true);
    }//GEN-LAST:event_EliminarDocDeLaColaActionPerformed

    private void CrearDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDocumento1ActionPerformed
        CrearDoc V = new CrearDoc();
        this.setVisible(false);
        V.setVisible(true);
    }//GEN-LAST:event_CrearDocumento1ActionPerformed

    private void EliminarDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocumento1ActionPerformed
        EliminarDocumento V7 = new EliminarDocumento();
        this.setVisible(false);
        V7.setVisible(true);
    }//GEN-LAST:event_EliminarDocumento1ActionPerformed

    private void EnviarAColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarAColaActionPerformed
        InsertarDocCola V = new InsertarDocCola();
        this.setVisible(false);
        V.setVisible(true);
    }//GEN-LAST:event_EnviarAColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton ColaArbol;
    private javax.swing.JButton ColaSecuencia;
    private javax.swing.JButton CrearDocumento1;
    private javax.swing.JButton EliminarDocDeLaCola;
    private javax.swing.JButton EliminarDocumento1;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JButton EnviarACola;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton LiberarImpresora;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VerUsuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
