/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author evaas
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AgregarUsuario = new javax.swing.JButton();
        CargarArchivo = new javax.swing.JButton();
        EliminarUsuario = new javax.swing.JButton();
        CrearDocumento = new javax.swing.JButton();
        VerUsuarios = new javax.swing.JButton();
        EliminarDocumento = new javax.swing.JButton();
        ColaSecuencia = new javax.swing.JButton();
        ColaArbol = new javax.swing.JButton();
        LiberarImpresora = new javax.swing.JButton();
        EliminarDocDeLaCola = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarUsuario.setText("Agregar Usuario");
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, -1));

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, -1));

        EliminarUsuario.setText("Eliminar Usuario");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 140, -1));

        CrearDocumento.setText("Crear Documento");
        CrearDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(CrearDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, -1));

        VerUsuarios.setText("Ver Usuarios");
        VerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(VerUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 140, -1));

        EliminarDocumento.setText("Eliminar Documento");
        EliminarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 210, -1));

        ColaSecuencia.setText("Cola de Impresión (secuencia)");
        ColaSecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaSecuenciaActionPerformed(evt);
            }
        });
        jPanel1.add(ColaSecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 210, -1));

        ColaArbol.setText("Cola de impresión (árbol)");
        ColaArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaArbolActionPerformed(evt);
            }
        });
        jPanel1.add(ColaArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 210, -1));

        LiberarImpresora.setText("Liberar Impresora");
        LiberarImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiberarImpresoraActionPerformed(evt);
            }
        });
        jPanel1.add(LiberarImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 210, -1));

        EliminarDocDeLaCola.setText("Eliminar Documento de la cola");
        EliminarDocDeLaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarDocDeLaColaActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarDocDeLaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 210, -1));

        Salir.setText("X");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 590, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        AgregarUsuario ventana2 = new AgregarUsuario();
        this.setVisible(false);
        ventana2.setVisible(true);
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void VerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerUsuariosActionPerformed
        VerUsuarios V6 = new VerUsuarios();
        this.setVisible(false);
        V6.setVisible(true);
    }//GEN-LAST:event_VerUsuariosActionPerformed

    private void ColaSecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaSecuenciaActionPerformed
        ColaSecuencia V5 = new ColaSecuencia();
        this.setVisible(false);
        V5.setVisible(true);
    }//GEN-LAST:event_ColaSecuenciaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void CrearDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDocumentoActionPerformed
        CrearDoc V3 = new CrearDoc();
        this.setVisible(false);
        V3.setVisible(true);
    }//GEN-LAST:event_CrearDocumentoActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        EliminarUsuario V4 = new EliminarUsuario();
        this.setVisible(false);
        V4.setVisible(true);
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void EliminarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocumentoActionPerformed
        EliminarDocumento V7 = new EliminarDocumento();
        this.setVisible(false);
        V7.setVisible(true);
    }//GEN-LAST:event_EliminarDocumentoActionPerformed

    private void ColaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaArbolActionPerformed
        ColaArbol V8 = new ColaArbol();
        this.setVisible(false);
        V8.setVisible(true);
    }//GEN-LAST:event_ColaArbolActionPerformed

    private void LiberarImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiberarImpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LiberarImpresoraActionPerformed

    private void EliminarDocDeLaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarDocDeLaColaActionPerformed
        EliminarDocCola V9 = new EliminarDocCola();
        this.setVisible(false);
        V9.setVisible(true);
    }//GEN-LAST:event_EliminarDocDeLaColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton ColaArbol;
    private javax.swing.JButton ColaSecuencia;
    private javax.swing.JButton CrearDocumento;
    private javax.swing.JButton EliminarDocDeLaCola;
    private javax.swing.JButton EliminarDocumento;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton LiberarImpresora;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VerUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
